// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	ID        uuid.UUID        `json:"id"`
	ConID     uuid.UUID        `json:"con_id"`
	Sender    string           `json:"sender"`
	Content   string           `json:"content"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
}

type Summary struct {
	ID             uuid.UUID        `json:"id"`
	Content        string           `json:"content"`
	ConversationID uuid.UUID        `json:"conversation_id"`
	PatientID      uuid.UUID        `json:"patient_id"`
	DoctorID       uuid.UUID        `json:"doctor_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID            uuid.UUID        `json:"id"`
	Email         string           `json:"email"`
	Username      string           `json:"username"`
	Role          string           `json:"role"`
	Experience    string           `json:"experience"`
	Location      string           `json:"location"`
	LicenseNumber string           `json:"license_number"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}
